### ISSUE TITLE
call for dataset

### ISSUE THREAD

**Issue by cf28920782519** [aditya1709/DTW_kmedoids#1]
hello, it's my honor to write this.  i read your code about dtw_kmedoids, but you may not upload the dataset. so, it is so hard to figure out the dataframe of your code. 
Can you send me a copy of data: Trajectories_training.hdf5  Labels_training.hdf5  ? please~very thank you!
my email is   liebesysu@gmail.com 
best wishes!

**Comment by CoffeeCandy** [comment]
> hello, it's my honor to write this. i read your code about dtw_kmedoids, but you may not upload the dataset. so, it is so hard to figure out the dataframe of your code.
> Can you send me a copy of data: Trajectories_training.hdf5 Labels_training.hdf5 ? please~very thank you!
> my email is [liebesysu@gmail.com](mailto:liebesysu@gmail.com)
> best wishes!
hello,do you get this datasets?could you please email me too,thank you very much,my email is 1282309187@qq.com

**Comment by aditya1709** [comment]
I am sorry, the dataset is part of a patent (pending) and cannot be put up. I would be happy to help incase you have any questions.
